apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-1
  template:
    metadata:
      labels:
        app: container-1
    spec:
      containers:
      - name: container-1
        image: gcr.io/kubernetesassignment-428818/container-1
        ports:
        - containerPort: 8080
